version: '3.9'

services:
  mysql:
    image: mysql:8
    container_name: my-mysql
    environment:
      MYSQL_ROOT_PASSWORD: Cheikh@1993
      MYSQL_DATABASE: sen_csu
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - spring_net

  spring-app:
    build: .
    container_name: spring-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/sen_csu
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Cheikh@1993
    depends_on:
      - mysql
    networks:
      - spring_net

volumes:
  mysql_data:

networks:
  spring_net:
